export type Difficulty = "easy" | "medium" | "hard";
export type WordBuckets = Record<Difficulty, string[]>;

export const WORDS_BY_DIFFICULTY: Record<string, WordBuckets> = {
  sports: {
    easy: [
      "football",
      "cricket",
      "bat",
      "ball",
      "goal",
      "run",
      "umpire",
      "coach",
      "stadium",
      "medal",
      "tennis",
      "helmet",
      "swim",
      "race",
      "referee",
      "kick",
      "pitch",
      "score",
      "team",
      "whistle",
      "jersey",
      "net",
      "hoop",
      "golf",
      "hockey",
      "kabaddi",
      "boxing",
      "cycling",
      "skiing",
      "trophy",
    ],
    medium: [
      "offside",
      "penalty",
      "wicket",
      "marathon",
      "gymnastics",
      "badminton",
      "relay race",
      "boxing ring",
      "scoreboard",
      "tournament",
      "archery",
      "surfing",
      "skateboarding",
      "powerplay",
      "free kick",
      "goalkeeper",
      "half time",
      "knockout",
      "inning",
      "spin bowling",
      "slam dunk",
      "triple jump",
      "foul",
      "substitution",
      "warm up",
      "time out",
      "home run",
      "long jump",
      "sprinter",
      "defense",
    ],
    hard: [
      "decathlon",
      "triathlon",
      "freestyle wrestling",
      "quarterback sneak",
      "hat-trick",
      "grand slam",
      "VAR review",
      "Ashes series",
      "photo finish",
      "fencing bout",
      "shot put technique",
      "Heisman Trophy",
      "Olympic qualifier",
      "butterfly stroke",
      "fielding position",
      "red card appeal",
      "draft combine",
      "playoff bracket",
      "world record attempt",
      "penalty shootout",
      "sudden death",
      "sportsmanship",
      "handball violation",
      "technical foul",
      "corner flag",
      "officiating crew",
      "round robin",
      "athletic scholarship",
      "press conference",
      "salary cap",
    ],
  },

  bollywood: {
    easy: [
      "Shah Rukh Khan",
      "Salman Khan",
      "Aamir Khan",
      "Ranbir Kapoor",
      "Deepika Padukone",
      "Alia Bhatt",
      "Hrithik Roshan",
      "Amitabh Bachchan",
      "Katrina Kaif",
      "Priyanka Chopra",
      "Varun Dhawan",
      "Anushka Sharma",
      "Ranveer Singh",
      "Kareena Kapoor",
      "Ajay Devgn",
      "3 Idiots",
      "Dangal",
      "Chennai Express",
      "PK",
      "War",
      "Pathaan",
      "Tiger",
      "Baahubali",
      "Sultan",
      "Ra.One",
      "Krrish",
      "Dilwale",
      "Barfi",
      "Student of the Year",
      "Kick",
    ],
    medium: [
      "Dilwale Dulhania Le Jayenge",
      "Kabhi Khushi Kabhie Gham",
      "Zindagi Na Milegi Dobara",
      "Bajirao Mastani",
      "Padmaavat",
      "Rockstar",
      "Tamasha",
      "Swades",
      "Lagaan",
      "Rang De Basanti",
      "Andhadhun",
      "Bhool Bhulaiyaa",
      "Don",
      "Chak De India",
      "My Name Is Khan",
      "Kal Ho Naa Ho",
      "Gully Boy",
      "Yeh Jawaani Hai Deewani",
      "Jab We Met",
      "Queen",
      "Drishyam",
      "Uri",
      "Barfi",
      "Special 26",
      "Haider",
      "Raazi",
      "Article 15",
      "Kahaani",
      "Lootera",
      "Pink",
    ],
    hard: [
      "Mughal-e-Azam",
      "Gangs of Wasseypur",
      "Sholay",
      "Guide",
      "Pyaasa",
      "Andaz Apna Apna",
      "Tumbbad",
      "Black Friday",
      "Udaan",
      "Masaan",
      "Devdas",
      "Mother India",
      "Satya",
      "Company",
      "Omkara",
      "Kaagaz Ke Phool",
      "Dil Se",
      "Talvar",
      "October",
      "Rocket Singh",
      "Sardar Udham",
      "Lagaan tax scene",
      "Basanti dance",
      "Gabbar Singh",
      "Raj Mandir cinema",
      "Item number",
      "Interval block",
      "Masala film",
      "Parallel cinema",
      "Box office clash",
    ],
  },

  hollywood: {
    easy: [
      "Titanic",
      "Avengers",
      "Batman",
      "Spider-Man",
      "Frozen",
      "Iron Man",
      "Harry Potter",
      "Superman",
      "Joker",
      "Lion King",
      "Hulk",
      "Captain America",
      "Thor",
      "Minions",
      "Cars",
      "Finding Nemo",
      "Deadpool",
      "Black Panther",
      "Wonder Woman",
      "Shrek",
      "Toy Story",
      "The Flash",
      "Aquaman",
      "Barbie",
      "Mission Impossible",
      "Gladiator",
      "The Matrix",
      "Avatar",
      "Rocky",
      "Jaws",
    ],
    medium: [
      "Inception",
      "Interstellar",
      "Jurassic Park",
      "Pirates of the Caribbean",
      "The Dark Knight",
      "Forrest Gump",
      "The Godfather",
      "Mad Max",
      "The Revenant",
      "The Wolf of Wall Street",
      "Fight Club",
      "The Social Network",
      "Gravity",
      "The Hunger Games",
      "The Notebook",
      "A Quiet Place",
      "The Prestige",
      "Django Unchained",
      "The Truman Show",
      "The Martian",
      "Up",
      "Inside Out",
      "Coco",
      "Oppenheimer",
      "Top Gun Maverick",
      "Black Swan",
      "La La Land",
      "Whiplash",
      "The Conjuring",
      "Doctor Strange",
    ],
    hard: [
      "Schindler's List",
      "No Country for Old Men",
      "A Clockwork Orange",
      "The Shawshank Redemption",
      "There Will Be Blood",
      "Blade Runner 2049",
      "The Grand Budapest Hotel",
      "Birdman",
      "Eternal Sunshine of the Spotless Mind",
      "The Departed",
      "Parasite",
      "Requiem for a Dream",
      "The Green Mile",
      "American Psycho",
      "The Pianist",
      "Se7en",
      "The Usual Suspects",
      "Her",
      "The Lighthouse",
      "Donnie Darko",
      "The Irishman",
      "Taxi Driver",
      "2001 A Space Odyssey",
      "Citizen Kane",
      "The Hateful Eight",
      "Pan's Labyrinth",
      "Moonlight",
      "Memento",
      "The Sixth Sense",
      "Glory",
    ],
  },

  music: {
    easy: [
      "guitar",
      "piano",
      "drum",
      "microphone",
      "singer",
      "concert",
      "DJ",
      "song",
      "album",
      "band",
      "rap",
      "pop",
      "rock",
      "dance",
      "stage",
      "lyrics",
      "beat",
      "chorus",
      "speaker",
      "radio",
      "headphones",
      "playlist",
      "violin",
      "flute",
      "tabla",
      "dhol",
      "harmonium",
      "keyboard",
      "amp",
      "whistle",
    ],
    medium: [
      "orchestra",
      "saxophone",
      "composer",
      "rapper",
      "music video",
      "producer",
      "studio",
      "remix",
      "acoustic",
      "bass guitar",
      "hip hop",
      "metal band",
      "EDM",
      "record label",
      "live show",
      "soundcheck",
      "backstage",
      "cover song",
      "duet",
      "karaoke",
      "violin solo",
      "symphony",
      "metronome",
      "playlist shuffle",
      "vinyl record",
      "platinum record",
      "Grammy Awards",
      "Billboard charts",
      "auto-tune",
      "improvisation",
    ],
    hard: [
      "crescendo",
      "falsetto",
      "counterpoint",
      "octave shift",
      "bridge section",
      "tempo change",
      "orchestration",
      "beat drop",
      "sampling",
      "sound engineering",
      "music production",
      "lyrical metaphor",
      "concept album",
      "world tour",
      "encore performance",
      "chart topper",
      "soundtrack score",
      "classical recital",
      "jazz improvisation",
      "baritone",
      "soprano",
      "treble clef",
      "bass clef",
      "syncopation",
      "modulation",
      "recording contract",
      "royalty payment",
      "studio session",
      "headline act",
      "music festival",
    ],
  },
};
