import type { Top9Question } from "./types";

type AnswerTuple = [text: string, points: number, ...aliases: string[]];

function q(
  id: string,
  categories: string | string[],
  prompt: string,
  answers: AnswerTuple[],
): Top9Question {
  return {
    id: `o-${id}`,
    categories: Array.isArray(categories) ? categories : [categories],
    prompt,
    source: "original",
    answers: answers.map(([text, points, ...aliases]) => ({
      text,
      points,
      ...(aliases.length ? { aliases } : {}),
    })),
  };
}

/**
 * Vybrid originals: nine answers per prompt, written with Indian game nights
 * in mind. Rankings are our estimates of what a crowd would say, not results
 * from a real survey. Points add up to roughly 100.
 */
export const originalQuestions: Top9Question[] = [
  // ---------------------------------------------------------------- everyday
  q(
    "pack-holiday",
    "home",
    "Name something people forget to pack for a holiday.",
    [
      ["Phone charger", 24, "charger", "cable"],
      ["Toothbrush", 18, "toothpaste"],
      ["Underwear", 12, "undies", "innerwear"],
      ["Passport", 10, "id", "tickets"],
      ["Medicines", 9, "medicine", "pills", "tablets"],
      ["Socks", 8],
      ["Sunscreen", 7, "sunblock"],
      ["Swimsuit", 6, "swimwear", "costume", "bikini"],
      ["Adapter", 6, "plug", "power bank"],
    ],
  ),
  q("morning-first", "home", "Name the first thing you do after waking up.", [
    ["Check my phone", 30, "phone", "scroll", "instagram", "whatsapp"],
    ["Brush teeth", 16, "brush"],
    ["Use the bathroom", 13, "toilet", "pee", "washroom"],
    ["Drink water", 10, "water"],
    ["Make tea or coffee", 9, "tea", "coffee", "chai"],
    ["Snooze the alarm", 8, "alarm", "snooze", "go back to sleep"],
    ["Stretch", 6, "yawn"],
    ["Pray", 4, "prayer"],
    ["Shower", 4, "bath"],
  ]),
  q(
    "lose-house",
    "home",
    "Name something people are always losing around the house.",
    [
      ["Keys", 28, "key", "car keys"],
      ["Phone", 18, "mobile"],
      ["TV remote", 15, "remote"],
      ["Glasses", 10, "spectacles", "specs", "sunglasses"],
      ["Wallet", 8, "purse"],
      ["Socks", 7, "sock"],
      ["Charger", 6],
      ["Hair ties", 4, "hair tie", "rubber band", "clips"],
      ["Pen", 4, "pens"],
    ],
  ),
  q(
    "phone-battery",
    "home",
    "Name something that drains your phone battery fast.",
    [
      ["Games", 22, "gaming"],
      ["Videos", 18, "youtube", "netflix", "streaming"],
      ["Social media", 16, "instagram", "reels", "tiktok", "facebook"],
      ["GPS", 12, "maps", "location", "navigation"],
      ["Bright screen", 9, "brightness", "screen"],
      ["Camera", 7, "photos"],
      ["Calls", 6, "video calls", "video call"],
      ["Bluetooth", 5],
      ["Old battery", 5, "old phone"],
    ],
  ),
  q(
    "bag-contents",
    "home",
    "Name something you'd find in almost any handbag.",
    [
      ["Wallet", 22, "purse", "money", "cash"],
      ["Phone", 17],
      ["Lipstick", 14, "lip balm", "makeup", "chapstick"],
      ["Keys", 12, "key"],
      ["Tissues", 9, "tissue", "napkins", "wipes"],
      ["Sanitizer", 8, "hand sanitizer"],
      ["Comb", 6, "hairbrush", "brush"],
      ["Mints", 6, "gum", "chewing gum"],
      ["Receipts", 6, "bills"],
    ],
  ),
  q("rain-do", "home", "Name something people do on a rainy day.", [
    ["Sleep", 20, "nap"],
    ["Watch movies", 18, "movie", "netflix", "tv"],
    ["Drink chai", 16, "tea", "coffee", "chai"],
    ["Eat pakoras", 14, "pakora", "pakodas", "bhajiya", "fritters", "snacks"],
    ["Read", 8, "book", "books"],
    ["Dance in the rain", 7, "dance", "get wet", "play in the rain"],
    ["Stay home", 7, "stay in"],
    ["Play board games", 5, "games", "cards"],
    ["Listen to music", 5, "music"],
  ]),
  q(
    "bathroom-things",
    "home",
    "Name something people do in the bathroom besides the obvious.",
    [
      ["Scroll on phone", 30, "phone", "instagram", "reels"],
      ["Sing", 20, "singing"],
      ["Read", 12, "newspaper", "book"],
      ["Cry", 9, "crying"],
      ["Think", 8, "overthink", "plan"],
      ["Practise speeches", 7, "talk to myself", "practice", "rehearse"],
      ["Hide from people", 6, "hide", "escape"],
      ["Take selfies", 4, "selfie"],
      ["Nap", 4, "sleep"],
    ],
  ),

  // ---------------------------------------------------------------- food
  q("pizza-topping", "food", "Name a popular pizza topping.", [
    ["Cheese", 22, "extra cheese", "mozzarella"],
    ["Pepperoni", 16],
    ["Mushroom", 12, "mushrooms"],
    ["Onion", 10, "onions"],
    ["Chicken", 10, "tandoori chicken", "bbq chicken"],
    ["Olives", 9, "olive", "black olives"],
    ["Paneer", 8],
    ["Capsicum", 7, "bell pepper", "peppers", "green pepper"],
    ["Corn", 6, "sweet corn"],
  ]),
  q(
    "midnight-snack",
    "food",
    "Name something people eat as a midnight snack.",
    [
      ["Maggi", 26, "instant noodles", "noodles", "ramen"],
      ["Chips", 16, "crisps", "lays"],
      ["Ice cream", 13],
      ["Chocolate", 11],
      ["Leftovers", 9, "leftover"],
      ["Biscuits", 8, "cookies"],
      ["Cereal", 6],
      ["Fruit", 6, "banana", "apple"],
      ["Toast", 5, "bread", "sandwich"],
    ],
  ),
  q("street-food", "food", "Name a street food you can't say no to.", [
    ["Pani puri", 26, "golgappa", "gol gappa", "puchka", "golgappe"],
    ["Momos", 18, "momo", "dumplings"],
    ["Chaat", 12, "papdi chaat", "bhel", "bhel puri"],
    ["Vada pav", 10, "vada pao"],
    ["Samosa", 9, "samosas"],
    ["Pav bhaji", 8],
    ["Chole bhature", 7, "chole", "bhature"],
    ["Kathi roll", 6, "roll", "frankie", "rolls"],
    ["Dosa", 4],
  ]),
  q("sandwich-filling", "food", "Name something you'd put in a sandwich.", [
    ["Cheese", 22],
    ["Tomato", 14, "tomatoes"],
    ["Cucumber", 12],
    ["Chicken", 11],
    ["Lettuce", 9, "salad", "greens"],
    ["Onion", 8, "onions"],
    ["Egg", 8, "eggs"],
    ["Potato", 8, "aloo"],
    ["Butter", 8, "mayo", "mayonnaise", "chutney"],
  ]),
  q("hot-drink", "food", "Name a drink people have when they're sick.", [
    ["Tea", 22, "chai", "ginger tea", "adrak chai"],
    ["Soup", 18],
    ["Haldi doodh", 14, "turmeric milk", "haldi milk", "golden milk"],
    ["Kadha", 12, "kada", "herbal tea"],
    ["Warm water", 10, "hot water", "water"],
    ["Juice", 8, "orange juice"],
    ["Lemon honey water", 6, "honey lemon", "lemon water", "honey"],
    ["ORS", 5, "electral", "electrolytes"],
    ["Coffee", 5],
  ]),
  q("cake-flavour", "food", "Name a flavour of cake.", [
    ["Chocolate", 34, "choco", "truffle"],
    ["Vanilla", 16],
    ["Red velvet", 12],
    ["Black forest", 10],
    ["Pineapple", 9],
    ["Butterscotch", 7],
    ["Strawberry", 5],
    ["Carrot", 4],
    ["Coffee", 3, "tiramisu", "mocha"],
  ]),
  q("fridge-always", "food", "Name something that's always in the fridge.", [
    ["Milk", 26],
    ["Water", 16, "water bottles", "cold water"],
    ["Eggs", 12, "egg"],
    ["Butter", 10],
    ["Curd", 9, "dahi", "yogurt", "yoghurt"],
    ["Vegetables", 8, "veggies", "sabzi"],
    ["Leftovers", 7, "leftover food"],
    ["Ketchup", 6, "sauce", "sauces"],
    ["Chocolate", 6],
  ]),

  // ---------------------------------------------------------------- desi life
  q(
    "wedding-see",
    "desi",
    "Name something you'll always see at an Indian wedding.",
    [
      ["Dancing", 20, "dance", "sangeet"],
      ["Food buffet", 16, "food", "buffet"],
      ["Relatives", 13, "aunties", "family"],
      ["Mehndi", 11, "henna", "mehendi"],
      ["Baraat", 9, "horse", "ghodi"],
      ["DJ", 8, "music", "loud music"],
      ["Photographer", 8, "photos", "photographers"],
      ["Fireworks", 8, "crackers"],
      ["Gifts", 7, "envelopes", "shagun"],
    ],
  ),
  q(
    "aunty-ask",
    "desi",
    "Name a question aunties always ask at family functions.",
    [
      ["When are you getting married?", 38, "marriage", "shaadi", "married"],
      ["What are your marks?", 14, "marks", "results", "grades"],
      ["How much do you earn?", 12, "salary", "package", "earn"],
      ["Have you gained weight?", 10, "weight", "fat", "thin"],
      ["When is the good news?", 8, "baby", "kids", "children"],
      ["What are you doing these days?", 6, "job", "career"],
      ["Why don't you visit?", 5, "visit"],
      ["Did you eat?", 4, "food", "eat"],
      ["Going abroad?", 3, "abroad", "foreign", "america"],
    ],
  ),
  q("mom-says", "desi", "Name something Indian moms always say.", [
    ["Eat something", 22, "eat", "have food", "khaana kha lo"],
    ["Wear a sweater", 14, "sweater", "jacket"],
    ["Sharma ji's son", 13, "sharma ji", "neighbour's kid", "compare"],
    ["Put your phone down", 12, "phone", "mobile"],
    ["I'm not your servant", 9, "servant"],
    ["Go to sleep", 8, "sleep", "sleep early"],
    ["Clean your room", 8, "clean", "room"],
    ["Ask your father", 7, "papa", "dad"],
    ["Where are you?", 7, "come home", "when are you coming"],
  ]),
  q("festival", "desi", "Name an Indian festival.", [
    ["Diwali", 32, "deepavali"],
    ["Holi", 22],
    ["Eid", 10, "ramzan", "ramadan"],
    ["Navratri", 8, "durga puja", "dussehra", "garba"],
    ["Raksha Bandhan", 7, "rakhi"],
    ["Christmas", 6, "xmas"],
    ["Ganesh Chaturthi", 6, "ganpati"],
    ["Pongal", 5, "sankranti", "makar sankranti", "lohri"],
    ["Onam", 4],
  ]),
  q("chai-with", "desi", "Name something people have with their chai.", [
    ["Biscuits", 30, "biscuit", "parle g", "cookies", "rusk"],
    ["Samosa", 16],
    ["Pakoras", 14, "pakora", "pakodas", "bhajiya"],
    ["Namkeen", 10, "bhujia", "mixture"],
    ["Toast", 8, "bread", "bun maska", "bun"],
    ["Mathri", 6],
    ["Gossip", 6, "gupshup", "news"],
    ["Newspaper", 5],
    ["Cake", 5],
  ]),
  q(
    "train-journey",
    "desi",
    "Name something you'd see on a long Indian train journey.",
    [
      ["Chai wala", 24, "chai", "tea seller"],
      ["Families with food", 16, "food", "home food", "tiffin"],
      ["Sleeping people", 12, "sleeping", "berths", "upper berth"],
      ["Card games", 10, "cards", "playing cards"],
      ["Crowds", 9, "crowd", "people"],
      ["Hawkers", 9, "vendors", "sellers"],
      ["TT checking tickets", 8, "ticket checker", "tt", "tc"],
      ["Fields", 6, "villages", "views", "scenery"],
      ["Chain pulling", 6, "delays", "late train"],
    ],
  ),
  q(
    "cricket-thing",
    "desi",
    "Name something you'd see at a gully cricket match.",
    [
      ["Broken window", 24, "window", "glass"],
      ["Plastic ball", 16, "tennis ball", "ball"],
      ["Arguments", 14, "fights", "fighting", "not out"],
      ["Bricks as stumps", 12, "bricks", "stumps", "wickets"],
      ["One tip one hand", 8, "rules"],
      ["Uncle yelling", 8, "neighbour", "angry uncle"],
      ["Kids", 7, "children"],
      ["Lost ball", 6, "ball in drain"],
      ["Bat", 5],
    ],
  ),

  // ---------------------------------------------------------------- family & love
  q("date-idea", "love", "Name a popular first date idea.", [
    ["Dinner", 28, "restaurant", "food"],
    ["Movie", 20, "cinema", "movies"],
    ["Coffee", 16, "cafe", "coffee date"],
    ["Walk", 9, "park", "beach"],
    ["Drinks", 8, "bar", "pub"],
    ["Mall", 6, "shopping"],
    ["Bowling", 5, "arcade", "gaming"],
    ["Concert", 4, "gig"],
    ["Picnic", 4],
  ]),
  q(
    "partner-annoying",
    "love",
    "Name a habit of your partner that annoys you.",
    [
      ["Snoring", 24, "snores"],
      ["Always on the phone", 18, "phone", "scrolling"],
      ["Being late", 12, "late"],
      ["Leaving clothes around", 10, "clothes", "messy", "mess"],
      ["Not listening", 9, "ignoring"],
      ["Stealing the blanket", 8, "blanket"],
      ["Toilet seat up", 7, "toilet seat"],
      ["Loud chewing", 6, "chewing"],
      ["Leaving lights on", 6, "lights"],
    ],
  ),
  q(
    "kids-excuse",
    "family",
    "Name an excuse kids give for not doing homework.",
    [
      ["The dog ate it", 26, "dog"],
      ["I forgot", 22, "forgot"],
      ["I was sick", 12, "sick", "ill", "fever"],
      ["Left it at home", 10, "at home"],
      ["Didn't understand it", 8, "too hard", "didn't understand"],
      ["No electricity", 7, "power cut", "light gone"],
      ["Wasn't told", 6, "no one told me"],
      ["Book was missing", 5, "lost it", "lost my book"],
      ["Guests came", 4, "relatives came", "guests"],
    ],
  ),
  q("grandparents-say", "family", "Name something grandparents always say.", [
    ["In our days", 30, "back in my day", "our time", "hamare zamane mein"],
    ["You've become so thin", 16, "thin", "weak", "eat more"],
    ["Eat more", 12, "eat"],
    ["Too much phone", 12, "phone", "mobile"],
    ["When will you marry?", 9, "marriage", "shaadi"],
    ["Sleep early", 7, "sleep"],
    ["Pray", 5, "god", "temple"],
    ["Respect elders", 5, "respect"],
    ["Wear warm clothes", 4, "sweater"],
  ]),

  // ---------------------------------------------------------------- work & school
  q(
    "office-meeting",
    "work",
    "Name something people do during a boring meeting.",
    [
      ["Check phone", 26, "phone", "scroll"],
      ["Doodle", 16, "draw", "doodling"],
      ["Sleep", 14, "nap", "doze off"],
      ["Pretend to take notes", 10, "notes", "take notes"],
      ["Check email", 9, "emails", "email"],
      ["Stay on mute", 8, "mute", "camera off"],
      ["Snack", 7, "eat"],
      ["Daydream", 6, "zone out"],
      ["Chat with colleagues", 4, "chat", "text"],
    ],
  ),
  q("school-bag", "work", "Name something you'd find in a school bag.", [
    ["Books", 24, "textbooks", "notebooks", "notebook"],
    ["Pencil box", 18, "pencils", "pens", "geometry box", "stationery"],
    ["Tiffin box", 16, "tiffin", "lunch box", "lunch"],
    ["Water bottle", 12, "bottle"],
    ["Homework", 8],
    ["Eraser", 6, "rubber"],
    ["Crumpled papers", 6, "papers", "chits"],
    ["Snacks", 5, "chocolate", "candy"],
    ["Handkerchief", 5, "hanky", "napkin"],
  ]),
  q("teacher-say", "work", "Name something teachers always say.", [
    ["Silence!", 24, "quiet", "keep quiet", "silence please"],
    ["Is this a fish market?", 16, "fish market"],
    ["Open your books", 12, "books"],
    ["Who is talking?", 10, "talking"],
    ["Get out of my class", 8, "get out", "out"],
    ["This will come in the exam", 8, "exam", "important"],
    ["Where is your homework?", 8, "homework"],
    ["Stand up", 7, "stand up on the bench"],
    ["I will call your parents", 7, "parents", "call your parents"],
  ]),
  q("sick-leave", "work", "Name a reason people give for taking a day off.", [
    ["Sick", 30, "fever", "ill", "not well", "cold"],
    ["Family function", 14, "wedding", "function"],
    ["Doctor's appointment", 12, "doctor", "appointment"],
    ["Food poisoning", 10, "stomach", "upset stomach"],
    ["Emergency", 9, "family emergency"],
    ["Car broke down", 7, "car", "transport"],
    ["Headache", 7, "migraine"],
    ["Mental health day", 6, "mental health", "burnout"],
    ["Grandma is sick", 5, "grandmother", "relative"],
  ]),
  q("job-dream", "work", "Name a job kids dream of having.", [
    ["Doctor", 18],
    ["Astronaut", 14],
    ["Cricketer", 13, "sportsperson", "athlete", "footballer"],
    ["Pilot", 12],
    ["Actor", 10, "film star", "movie star", "actress"],
    ["Police officer", 10, "police", "cop"],
    ["Teacher", 9],
    ["YouTuber", 8, "influencer", "streamer"],
    ["Firefighter", 6, "fireman"],
  ]),

  // ---------------------------------------------------------------- just for fun
  q("superpower", "everyday", "Name a superpower people wish they had.", [
    ["Flying", 26, "fly", "flight"],
    ["Invisibility", 18, "invisible"],
    ["Teleportation", 16, "teleport"],
    ["Time travel", 12, "time"],
    ["Reading minds", 10, "mind reading", "telepathy"],
    ["Super strength", 6, "strength", "strong"],
    ["Healing", 5, "heal"],
    ["Super speed", 4, "speed", "fast"],
    ["Stopping time", 3, "freeze time"],
  ]),
  q(
    "zombie-weapon",
    "everyday",
    "Name something you'd grab to fight off zombies.",
    [
      ["Baseball bat", 22, "bat", "cricket bat"],
      ["Knife", 16, "kitchen knife"],
      ["Gun", 14],
      ["Frying pan", 12, "pan", "tawa"],
      ["Axe", 10],
      ["Chair", 7],
      ["Broom", 7, "jhadu", "mop"],
      ["Hockey stick", 6, "stick", "lathi"],
      ["Chappal", 6, "slipper", "slippers", "shoe"],
    ],
  ),
  q(
    "desert-island",
    "everyday",
    "Name something you'd take to a desert island.",
    [
      ["Phone", 18, "mobile"],
      ["Water", 16],
      ["Knife", 12, "swiss knife"],
      ["Food", 12, "snacks"],
      ["Lighter", 10, "matches", "fire"],
      ["Book", 9, "books"],
      [
        "My partner",
        8,
        "wife",
        "husband",
        "girlfriend",
        "boyfriend",
        "best friend",
      ],
      ["Tent", 8, "shelter"],
      ["Sunscreen", 7],
    ],
  ),
  q("scared-of", "everyday", "Name something lots of people are scared of.", [
    ["Spiders", 20, "spider"],
    ["Snakes", 18, "snake"],
    ["Heights", 14],
    ["Ghosts", 12, "ghost", "the dark", "dark"],
    ["Cockroaches", 10, "cockroach"],
    ["Public speaking", 8, "speaking", "stage"],
    ["Clowns", 6, "clown"],
    ["Dentist", 6, "injections", "needles", "doctor"],
    ["Death", 6, "dying"],
  ]),
  q("animal-pet", "everyday", "Name an animal people keep as a pet.", [
    ["Dog", 34, "puppy", "dogs"],
    ["Cat", 24, "kitten", "cats"],
    ["Fish", 12, "goldfish"],
    ["Parrot", 8, "bird", "budgie"],
    ["Rabbit", 7, "bunny"],
    ["Hamster", 5, "guinea pig", "mouse"],
    ["Turtle", 4, "tortoise"],
    ["Snake", 3],
    ["Cow", 3],
  ]),
  q(
    "party-song",
    "everyday",
    "Name something that always happens at a house party.",
    [
      ["Someone gets drunk", 18, "drunk", "drinking"],
      ["Dancing", 16, "dance"],
      ["Neighbours complain", 13, "neighbours", "noise", "police"],
      ["Loud music", 12, "music"],
      ["Something breaks", 9, "broken", "breaks"],
      ["Someone falls asleep", 9, "sleeps", "passes out"],
      ["Food runs out", 8, "food"],
      ["Games", 8, "drinking games", "truth or dare"],
      ["Selfies", 7, "photos", "pictures"],
    ],
  ),
  q("excuse-late", "everyday", "Name an excuse for being late.", [
    ["Traffic", 34, "jam", "traffic jam"],
    ["Overslept", 18, "slept", "alarm", "woke up late"],
    ["Car trouble", 10, "car", "flat tyre", "puncture"],
    ["Couldn't find keys", 8, "keys"],
    ["Bus was late", 8, "bus", "train", "metro"],
    ["Rain", 7, "weather"],
    ["Family emergency", 6, "emergency"],
    ["Phone died", 5, "phone"],
    ["Got lost", 4, "lost", "wrong way"],
  ]),
  q(
    "movie-snack",
    "everyday",
    "Name something people do at the cinema that annoys others.",
    [
      ["Talking", 26, "talk"],
      ["Using phone", 20, "phone", "screen"],
      ["Kicking seats", 14, "kicking", "seat"],
      ["Loud eating", 10, "eating", "popcorn", "chewing"],
      ["Coming late", 8, "late"],
      ["Spoilers", 7, "spoiling"],
      ["Crying babies", 6, "baby", "kids"],
      ["Hogging the armrest", 5, "armrest"],
      ["Snoring", 4, "sleeping"],
    ],
  ),
  // ---------------------------------------------------------------- more desi life
  q(
    "indian-kitchen",
    ["desi", "food"],
    "Name something you'd find in every Indian kitchen.",
    [
      ["Pressure cooker", 26, "cooker"],
      ["Masala dabba", 18, "spice box", "masala box", "spices"],
      ["Tawa", 12, "griddle", "pan"],
      ["Rolling pin", 10, "belan", "chakla belan", "chakla"],
      ["Steel utensils", 9, "steel plates", "steel glasses", "utensils"],
      ["Pickle jars", 8, "achaar", "pickle", "achar"],
      ["Mixer grinder", 7, "mixie", "mixer", "grinder"],
      ["Tea strainer", 5, "strainer", "chai strainer"],
      ["Plastic bags stash", 5, "plastic bags", "polythene"],
    ],
  ),
  q(
    "bollywood-actor",
    ["desi", "popculture"],
    "Name a Bollywood actor everyone knows.",
    [
      ["Shah Rukh Khan", 30, "srk", "shahrukh", "shah rukh"],
      ["Salman Khan", 18, "salman", "bhai"],
      ["Amitabh Bachchan", 16, "amitabh", "big b", "bachchan"],
      ["Aamir Khan", 9, "aamir"],
      ["Akshay Kumar", 8, "akshay", "khiladi"],
      ["Hrithik Roshan", 6, "hrithik"],
      ["Ranbir Kapoor", 5, "ranbir"],
      ["Ranveer Singh", 4, "ranveer"],
      ["Ajay Devgn", 4, "ajay devgan", "ajay"],
    ],
  ),
  q("indian-sweet", ["desi", "food"], "Name a popular Indian sweet.", [
    ["Gulab jamun", 26, "gulab jamoon", "jamun"],
    ["Rasgulla", 16, "rosogolla", "rasgolla"],
    ["Jalebi", 14, "jilebi"],
    ["Kaju katli", 12, "kaju barfi", "kaju"],
    ["Ladoo", 10, "laddoo", "laddu", "motichoor"],
    ["Barfi", 7, "burfi"],
    ["Rasmalai", 6, "ras malai"],
    ["Halwa", 5, "gajar halwa", "sooji halwa"],
    ["Peda", 4, "pedha"],
  ]),
  q("dad-says", ["desi", "family"], "Name something Indian dads always say.", [
    [
      "Switch off the lights",
      24,
      "lights",
      "switch off the fan",
      "electricity bill",
    ],
    [
      "Do you know how much this costs?",
      16,
      "money doesn't grow on trees",
      "waste of money",
      "money",
    ],
    ["Ask your mother", 12, "ask mummy", "mother"],
    ["Study hard", 11, "study", "focus on studies"],
    ["When I was your age", 10, "in my time", "my days"],
    ["Where is the remote?", 8, "remote"],
    ["Get off the phone", 7, "phone", "mobile"],
    ["Beta, come here", 6, "come here", "beta"],
    ["Be home by 9", 6, "come home early", "curfew"],
  ]),
  q(
    "bargain",
    ["desi", "money"],
    "Name something people bargain for in India.",
    [
      ["Auto fare", 24, "auto", "rickshaw", "cab fare"],
      ["Vegetables", 20, "sabzi", "veggies", "fruits"],
      ["Clothes", 16, "kurtas", "street shopping"],
      ["Souvenirs", 8, "handicrafts", "tourist stuff"],
      ["Jewellery", 8, "earrings", "bangles", "jewelry"],
      ["Shoes", 7, "chappals", "footwear"],
      ["Rent", 6, "house rent"],
      ["Electronics", 6, "phone cover", "earphones"],
      ["Furniture", 5],
    ],
  ),
  q("indian-breakfast", ["desi", "food"], "Name a popular Indian breakfast.", [
    ["Paratha", 22, "aloo paratha", "parantha"],
    ["Poha", 18, "pohe"],
    ["Idli", 14, "idly"],
    ["Dosa", 12, "masala dosa"],
    ["Upma", 9],
    ["Bread omelette", 8, "omelette", "eggs", "anda bread"],
    ["Puri bhaji", 7, "aloo puri", "puri sabzi", "poori"],
    ["Chole bhature", 5, "chole"],
    ["Sandwich", 5, "bread butter", "toast"],
  ]),
  q(
    "indian-road",
    ["desi", "travel"],
    "Name something you'd see or hear on an Indian road.",
    [
      ["Honking", 28, "horns", "horn"],
      ["Cows", 16, "cow", "animals", "dogs"],
      ["Potholes", 12, "pothole", "bad roads"],
      ["Autos", 10, "auto rickshaws", "rickshaws"],
      ["Traffic jam", 9, "traffic"],
      ["Wrong-side drivers", 8, "wrong side", "rash driving"],
      ["Street vendors", 7, "hawkers", "vendors"],
      ["Traffic police", 5, "police", "cops"],
      ["Bikes with 4 people", 5, "triple riding", "bikes", "scooters"],
    ],
  ),
  q(
    "hill-station",
    ["desi", "travel"],
    "Name a hill station Indians love to visit.",
    [
      ["Shimla", 22],
      ["Manali", 20],
      ["Ooty", 12, "ooty hills", "udhagamandalam"],
      ["Darjeeling", 10],
      ["Mussoorie", 9, "mussorie"],
      ["Nainital", 8],
      ["Munnar", 7],
      ["Kodaikanal", 6, "kodai"],
      ["Gangtok", 6, "sikkim"],
    ],
  ),
  q(
    "wedding-menu",
    ["desi", "food"],
    "Name something on every Indian wedding menu.",
    [
      ["Paneer", 20, "paneer butter masala", "shahi paneer"],
      ["Gulab jamun", 16, "sweets", "dessert"],
      ["Biryani", 12, "pulao", "rice"],
      ["Naan", 11, "roti", "tandoori roti"],
      ["Dal makhani", 10, "dal"],
      ["Chaat counter", 10, "chaat", "pani puri", "golgappa"],
      ["Ice cream", 8, "kulfi"],
      ["Paan", 7, "meetha paan"],
      ["Soup", 6, "tomato soup"],
    ],
  ),
  q(
    "parents-call",
    ["desi", "family"],
    "Name a reason Indian parents call their kids.",
    [
      ["Did you eat?", 28, "food", "have you eaten", "eat"],
      ["When are you coming home?", 16, "coming home", "come home"],
      ["Just checking in", 13, "just like that", "checking"],
      ["Marriage talk", 10, "marriage", "shaadi", "rishta"],
      ["Relative news", 9, "gossip", "relatives"],
      ["Weather warning", 7, "weather", "wear a sweater"],
      ["Tech help", 7, "phone problem", "whatsapp help", "tech"],
      ["Money", 5, "bills"],
      ["Wrong number", 5, "pocket dial", "by mistake"],
    ],
  ),
  q(
    "cricketer",
    ["desi", "sports"],
    "Name a cricketer everyone in India knows.",
    [
      ["Sachin Tendulkar", 30, "sachin", "tendulkar"],
      ["Virat Kohli", 22, "virat", "kohli"],
      ["MS Dhoni", 20, "dhoni", "mahi", "ms dhoni"],
      ["Rohit Sharma", 8, "rohit", "hitman"],
      ["Kapil Dev", 6, "kapil"],
      ["Sourav Ganguly", 5, "dada", "ganguly", "saurav ganguly"],
      ["Rahul Dravid", 4, "dravid"],
      ["Yuvraj Singh", 3, "yuvraj", "yuvi"],
      ["Jasprit Bumrah", 2, "bumrah"],
    ],
  ),
  q(
    "diwali-do",
    ["desi", "holidays"],
    "Name something people do during Diwali.",
    [
      ["Light diyas", 22, "diyas", "lamps", "candles", "lights"],
      ["Burst crackers", 18, "crackers", "fireworks", "patakhe"],
      ["Eat sweets", 14, "sweets", "mithai"],
      ["Clean the house", 12, "cleaning", "clean"],
      ["Make rangoli", 9, "rangoli"],
      ["Lakshmi puja", 8, "puja", "pray", "pooja"],
      ["Wear new clothes", 7, "new clothes", "dress up"],
      ["Shopping", 5, "buy gold", "shop"],
      ["Play cards", 5, "cards", "teen patti", "gamble"],
    ],
  ),
  q(
    "guest-only",
    ["desi", "home"],
    "Name something Indian homes save only for guests.",
    [
      ["Good crockery", 26, "crockery", "dinner set", "glass set", "plates"],
      ["Fancy biscuits", 16, "biscuits", "cookies"],
      ["New bedsheets", 12, "bedsheets", "sheets"],
      ["Dry fruits", 10, "kaju badam", "nuts"],
      ["Sofa covers off", 9, "sofa", "sofa covers"],
      ["Fancy towels", 8, "towels"],
      ["Sweets", 7, "mithai"],
      ["Cold drinks", 6, "soft drinks", "coke", "juice"],
      ["Guest room", 6, "room"],
    ],
  ),
  q("indian-tv", ["desi", "popculture"], "Name a popular Indian TV show.", [
    ["Kaun Banega Crorepati", 20, "kbc"],
    ["Bigg Boss", 16, "big boss"],
    [
      "Taarak Mehta Ka Ooltah Chashmah",
      15,
      "taarak mehta",
      "tmkoc",
      "tarak mehta",
    ],
    ["The Kapil Sharma Show", 12, "kapil sharma", "comedy nights"],
    ["CID", 10],
    ["Ramayan", 8, "ramayana"],
    ["Mahabharat", 7, "mahabharata"],
    ["Indian Idol", 6],
    ["Shark Tank India", 6, "shark tank"],
  ]),
  q(
    "desi-bathroom",
    ["desi", "home"],
    "Name something you'd find in a desi bathroom.",
    [
      ["Bucket", 28, "balti"],
      ["Mug", 22, "lota", "dabba"],
      ["Geyser", 12, "water heater", "immersion rod", "heater"],
      ["Soap", 10],
      ["Bathroom slippers", 8, "slippers", "chappals"],
      ["Stool", 6, "patla", "small stool"],
      ["Hair oil", 5, "oil", "coconut oil"],
      ["Toothbrush holder", 5, "toothbrush"],
      ["Washing powder", 4, "detergent", "surf"],
    ],
  ),
  q(
    "food-city",
    ["desi", "food", "travel"],
    "Name an Indian city famous for its food.",
    [
      ["Delhi", 20, "old delhi", "chandni chowk"],
      ["Hyderabad", 16],
      ["Lucknow", 14],
      ["Amritsar", 11],
      ["Mumbai", 11, "bombay"],
      ["Kolkata", 9, "calcutta"],
      ["Indore", 7],
      ["Chennai", 6, "madras"],
      ["Jaipur", 6],
    ],
  ),
  q(
    "power-cut",
    ["desi", "home"],
    "Name something people do during a power cut.",
    [
      ["Complain", 20, "curse", "call the electricity office"],
      ["Light candles", 16, "candles", "torch", "emergency light"],
      ["Sit outside", 14, "go to the terrace", "balcony", "go outside"],
      ["Fan themselves", 12, "hand fan", "newspaper fan", "fan"],
      ["Check the inverter", 10, "inverter", "generator"],
      ["Sleep", 9, "nap"],
      ["Save phone battery", 7, "phone battery", "power bank"],
      ["Chat with family", 6, "talk", "antakshari", "play games"],
      ["Ask the neighbours", 6, "neighbours", "check neighbours"],
    ],
  ),
  q(
    "road-trip",
    ["desi", "travel"],
    "Name something Indian families pack for a road trip.",
    [
      ["Snacks", 26, "chips", "namkeen", "food"],
      ["Aloo paratha", 14, "parathas", "home food", "puri"],
      ["Water bottles", 13, "water"],
      ["Songs playlist", 10, "music", "songs", "antakshari"],
      ["Pillow", 8, "pillows", "blanket"],
      ["Medicines", 8, "vomit medicine", "avomine", "motion sickness"],
      ["Phone charger", 8, "charger"],
      ["Plastic bags", 7, "vomit bags", "bags"],
      ["Sunglasses", 6, "shades"],
    ],
  ),
  q(
    "family-whatsapp",
    ["desi", "family"],
    "Name something you always see in a family WhatsApp group.",
    [
      ["Good morning messages", 30, "good morning", "flowers"],
      ["Forwards", 18, "forwarded messages", "forwarded as received"],
      ["Birthday wishes", 12, "birthdays", "wishes"],
      ["Fake news", 10, "fake news", "rumours"],
      ["Festival greetings", 9, "festival wishes", "happy diwali"],
      ["Jokes", 7, "memes"],
      ["Health tips", 6, "home remedies", "health"],
      ["Baby photos", 4, "photos", "pictures"],
      ["Political fights", 4, "politics", "arguments"],
    ],
  ),
  q("chai-add", ["desi", "food"], "Name something people add to chai.", [
    ["Sugar", 24],
    ["Ginger", 20, "adrak"],
    ["Elaichi", 16, "cardamom"],
    ["Milk", 12],
    ["Chai masala", 9, "masala", "tea masala"],
    ["Tulsi", 6, "basil"],
    ["Cloves", 5, "laung"],
    ["Black pepper", 4, "pepper", "kali mirch"],
    ["Lemongrass", 4, "gavti chaha"],
  ]),
  q(
    "bollywood-movie",
    ["desi", "popculture"],
    "Name a Bollywood movie everyone has seen.",
    [
      ["Dilwale Dulhania Le Jayenge", 22, "ddlj"],
      ["Sholay", 18],
      ["3 Idiots", 16, "three idiots"],
      ["Kabhi Khushi Kabhie Gham", 10, "k3g", "kabhi khushi"],
      ["Hera Pheri", 9],
      ["Kuch Kuch Hota Hai", 8, "kkhh"],
      ["Lagaan", 6],
      ["Dangal", 6],
      ["PK", 5],
    ],
  ),
  q(
    "holi-party",
    ["desi", "holidays"],
    "Name something you'd see at a Holi party.",
    [
      ["Colours", 30, "gulal", "colors", "abeer"],
      ["Water balloons", 16, "balloons", "water"],
      ["Pichkari", 14, "water gun", "water guns"],
      ["Thandai", 10, "bhang"],
      ["Dancing", 9, "dance", "music"],
      ["Gujiya", 8, "sweets"],
      ["White clothes", 6, "white kurta"],
      ["Wet people", 4, "soaked"],
      ["Stained faces", 3, "coloured faces"],
    ],
  ),
  q(
    "exam-night",
    ["desi", "work"],
    "Name something students do the night before an exam.",
    [
      ["Cram", 24, "study all night", "study", "mug up"],
      ["Drink chai", 14, "coffee", "chai", "tea"],
      ["Panic", 14, "cry", "stress"],
      ["Pray", 10, "prayer", "go to temple"],
      ["Group call", 9, "call friends", "group study"],
      ["Check the syllabus", 8, "syllabus", "important questions"],
      ["Make cheat notes", 7, "notes", "chits"],
      ["Watch YouTube summaries", 7, "youtube", "videos"],
      ["Sleep early", 7, "sleep"],
    ],
  ),
  q(
    "visit-gift",
    ["desi", "home"],
    "Name something people bring when visiting an Indian home.",
    [
      ["Sweets", 32, "mithai", "box of sweets"],
      ["Fruits", 18, "fruit basket"],
      ["Dry fruits", 14, "kaju badam", "dry fruit box"],
      ["Chocolates", 10, "chocolate", "cadbury"],
      ["Flowers", 7, "bouquet"],
      ["Namkeen", 6, "snacks"],
      ["Cake", 5],
      ["Toys for kids", 4, "toys"],
      ["Cash envelope", 4, "shagun", "money"],
    ],
  ),
  q(
    "weekend-outing",
    ["desi", "travel"],
    "Name a place families go for a weekend outing.",
    [
      ["Mall", 26, "shopping mall"],
      ["Movies", 16, "cinema", "movie", "pvr"],
      ["Restaurant", 14, "eating out", "dinner"],
      ["Relatives' house", 10, "relatives", "nani's house"],
      ["Park", 9, "garden"],
      ["Temple", 8, "mandir", "gurudwara", "church"],
      ["Beach", 7],
      ["Resort", 5, "farmhouse"],
      ["Long drive", 5, "drive"],
    ],
  ),
  q(
    "paan-shop",
    ["desi", "money"],
    "Name something you can buy at a paan shop.",
    [
      ["Paan", 26, "meetha paan"],
      ["Cigarettes", 18, "cigarette"],
      ["Chewing gum", 12, "gum"],
      ["Mouth freshener", 10, "saunf", "supari", "mukhwas"],
      ["Toffees", 9, "candy", "chocolates"],
      ["Cold drinks", 8, "soda", "soft drinks"],
      ["Chips", 7, "snacks"],
      ["Matchbox", 5, "lighter"],
      ["Phone recharge", 5, "recharge"],
    ],
  ),
  q(
    "maggi-add",
    ["desi", "food"],
    "Name something people add to their Maggi.",
    [
      ["Vegetables", 24, "veggies", "peas", "capsicum"],
      ["Cheese", 20],
      ["Egg", 14, "eggs", "anda"],
      ["Onion", 12, "onions"],
      ["Extra masala", 9, "masala", "tastemaker"],
      ["Butter", 7],
      ["Ketchup", 6, "sauce"],
      ["Green chilli", 5, "chilli", "mirchi"],
      ["Lemon", 3, "nimbu"],
    ],
  ),
  q(
    "parent-jobs",
    ["desi", "work", "family"],
    "Name a career Indian parents dream of for their kids.",
    [
      ["Doctor", 30],
      ["Engineer", 24, "software engineer", "it"],
      ["IAS officer", 14, "ias", "ips", "civil services", "upsc"],
      ["Government job", 9, "sarkari naukri", "government"],
      ["CA", 7, "chartered accountant"],
      ["Lawyer", 5],
      ["Bank job", 4, "banker"],
      ["Professor", 4, "teacher"],
      ["Pilot", 3],
    ],
  ),
  q(
    "mom-bag",
    ["desi", "family"],
    "Name something that's always in an Indian mom's handbag.",
    [
      ["Tissues", 18, "handkerchief", "napkins"],
      ["Safety pins", 16, "pins"],
      ["Snacks", 14, "biscuits", "food"],
      ["Medicines", 12, "crocin", "pills"],
      ["Keys", 10],
      ["Loose change", 9, "money", "cash"],
      ["Comb", 8],
      ["Saunf", 7, "mouth freshener", "elaichi"],
      ["Old bills", 6, "receipts", "bills"],
    ],
  ),
  q(
    "monsoon-problems",
    ["desi", "travel"],
    "Name a problem cities face in the monsoon.",
    [
      ["Waterlogging", 30, "flooding", "floods", "water on roads"],
      ["Traffic jams", 18, "traffic"],
      ["Potholes", 14],
      ["Power cuts", 10, "no electricity"],
      ["Mosquitoes", 9, "dengue", "malaria"],
      ["Clothes won't dry", 6, "wet clothes"],
      ["Leaking roofs", 5, "leaks", "seepage"],
      ["Mud", 4, "muddy roads", "slippery roads"],
      ["Colds", 4, "cold", "flu", "fever"],
    ],
  ),
  q(
    "function-fights",
    ["desi", "family"],
    "Name something relatives fight about at family functions.",
    [
      ["Food", 20, "catering"],
      ["Who wasn't invited", 16, "invitations", "not invited"],
      ["Gifts", 14, "shagun", "presents"],
      ["Old grudges", 12, "old fights", "past"],
      ["Seating", 9, "chairs", "who sits where"],
      ["Money", 9, "expenses"],
      ["Marriage talk", 8, "marriage", "rishta"],
      ["Politics", 7],
      ["Photos", 5, "family photo"],
    ],
  ),
];
