import type { Tone } from "@/lib/games";

/**
 * Imposter word bank. Each entry is "Word|hint": the hint is a vague nudge
 * the imposter can get (when hints are on) without giving the word away.
 * Desi categories come first; the classic ones keep mixed groups happy.
 */

export interface ImposterCategory {
  id: string;
  label: string;
  emoji: string;
  tone: Tone;
  desi: boolean;
  words: string[];
}

export interface ImposterWord {
  word: string;
  hint: string;
  categoryId: string;
}

export const imposterCategories: ImposterCategory[] = [
  {
    id: "desi-food",
    label: "Desi khana",
    emoji: "🍛",
    tone: "orange",
    desi: true,
    words: [
      "Biryani|Rice",
      "Butter Chicken|Creamy",
      "Masala Dosa|South",
      "Idli|Steam",
      "Rajma Chawal|Sunday",
      "Rava Kesari|Saffron",
      "Gulab Jamun|Syrup",
      "Rasgulla|Bengal",
      "Pav Bhaji|Butter",
      "Dal Makhani|Black",
      "Aloo Paratha|Breakfast",
      "Dhokla|Gujarat",
      "Poha|Indore",
      "Masala Chai|Kettle",
      "Khichdi|Comfort",
      "Paneer Tikka|Tandoor",
      "Gajar Halwa|Winter",
      "Pakora|Monsoon",
      "Litti Chokha|Bihar",
      "Kadhi Chawal|Yoghurt",
      "Rogan Josh|Kashmir",
      "Sarson da Saag|Makki",
      "Upma|Semolina",
      "Kaju Katli|Diamond",
      "Nimbu Pani|Summer",
      "Mango Pickle|Jar",
      "Thali|Plate",
    ],
  },
  {
    id: "street-food",
    label: "Street food",
    emoji: "🥟",
    tone: "yellow",
    desi: true,
    words: [
      "Golgappe|Water",
      "Bhel Puri|Chowpatty",
      "Sev Puri|Crunchy",
      "Dahi Puri|Curd",
      "Papdi Chaat|Plate",
      "Aloo Tikki|Patty",
      "Ragda Pattice|Mumbai",
      "Vada Pav|Mumbai",
      "Dabeli|Kutch",
      "Samosa|Triangle",
      "Kachori|Flaky",
      "Jalebi|Spiral",
      "Momos|Chutney",
      "Chowmein|Cart",
      "Manchurian|Desi-Chinese",
      "Egg Roll|Kolkata",
      "Kathi Roll|Wrap",
      "Shawarma|Late night",
      "Chicken Tikka|Skewer",
      "Galouti Kebab|Lucknow",
      "Bun Maska|Irani cafe",
      "Cutting Chai|Half",
      "Bhutta|Lemon",
      "Shakarkandi|Winter",
      "Ganne Ka Juice|Machine",
      "Nimbu Soda|Fizzy",
      "Lassi|Glass",
      "Kulfi|Matka",
      "Ice Gola|Syrup",
      "Rabdi Jalebi|Combo",
      "Chole Bhature|Fried",
      "Misal Pav|Kolhapur",
      "Mirchi Bajji|Hyderabad",
      "Chinese Bhel|Fusion",
      "Fruit Chaat|Masala",
    ],
  },
  {
    id: "bollywood-movies",
    label: "Bollywood movies",
    emoji: "🎬",
    tone: "red",
    desi: true,
    words: [
      "Sholay|Classic",
      "DDLJ|Train",
      "3 Idiots|College",
      "Lagaan|Tax",
      "Kabhi Khushi Kabhie Gham|Family",
      "Dangal|Wrestling",
      "PK|Alien",
      "Zindagi Na Milegi Dobara|Spain",
      "Hera Pheri|Phone",
      "Andaz Apna Apna|Comedy",
      "Gangs of Wasseypur|Revenge",
      "Kuch Kuch Hota Hai|Friendship",
      "Jab We Met|Train",
      "Taare Zameen Par|Teacher",
      "Chak De India|Hockey",
      "Munna Bhai MBBS|Hospital",
      "Bajrangi Bhaijaan|Border",
      "Kal Ho Naa Ho|New York",
      "Om Shanti Om|Rebirth",
      "Queen|Paris",
      "Gully Boy|Rap",
      "Dil Chahta Hai|Goa",
      "Yeh Jawaani Hai Deewani|Trek",
      "Rang De Basanti|Students",
      "Bahubali|Kingdom",
      "RRR|Dance",
      "Pathaan|Spy",
      "Jawan|Bald",
      "Animal|Violence",
      "Stree|Ghost",
      "Golmaal|Prank",
      "Dhoom|Bikes",
      "Krrish|Superhero",
      "Devdas|Heartbreak",
      "Mughal-e-Azam|Royal",
      "Swades|NASA",
      "Welcome|Gangsters",
      "Barfi|Silent",
      "Kahaani|Pregnant",
      "Drishyam|Alibi",
    ],
  },
  {
    id: "bollywood-stars",
    label: "Filmy stars & characters",
    emoji: "🌟",
    tone: "pink",
    desi: true,
    words: [
      "Shah Rukh Khan|Arms",
      "Salman Khan|Bhai",
      "Aamir Khan|Perfection",
      "Amitabh Bachchan|Baritone",
      "Deepika Padukone|Tall",
      "Priyanka Chopra|Abroad",
      "Alia Bhatt|Young",
      "Ranveer Singh|Energy",
      "Ranbir Kapoor|Family",
      "Katrina Kaif|Dance",
      "Kareena Kapoor|Bebo",
      "Akshay Kumar|Fitness",
      "Hrithik Roshan|Dance",
      "Rajinikanth|Style",
      "Madhuri Dixit|Smile",
      "Sridevi|Legend",
      "Rekha|Mystery",
      "Govinda|Comedy",
      "Ajay Devgn|Serious",
      "Shahid Kapoor|Chocolate",
      "Vicky Kaushal|Army",
      "Kartik Aaryan|Monologue",
      "Nawazuddin Siddiqui|Method",
      "Pankaj Tripathi|Calm",
      "Kangana Ranaut|Outspoken",
      "Anushka Sharma|Cricket",
      "Sunny Deol|Handpump",
      "Mithun Chakraborty|Disco",
      "Johnny Lever|Funny",
      "Arijit Singh|Sad",
      "Lata Mangeshkar|Voice",
      "Kishore Kumar|Yodel",
      "A.R. Rahman|Oscar",
      "Allu Arjun|Pushpa",
      "Prabhas|Epic",
      "Diljit Dosanjh|Punjab",
      "Karan Johar|Talk",
      "Farah Khan|Choreographer",
      "Circuit|Sidekick",
      "Poo|Attitude",
      "Chatur|Speech",
      "Manjulika|Haunted",
    ],
  },
  {
    id: "cricket",
    label: "Cricket",
    emoji: "🏏",
    tone: "green",
    desi: true,
    words: [
      "Virat Kohli|Aggression",
      "MS Dhoni|Calm",
      "Sachin Tendulkar|God",
      "Rohit Sharma|Hitman",
      "Jasprit Bumrah|Action",
      "Kapil Dev|1983",
      "Sourav Ganguly|Shirt",
      "Rahul Dravid|Wall",
      "Yuvraj Singh|Sixes",
      "IPL|Auction",
      "World Cup|Trophy",
      "Yorker|Toes",
      "Googly|Spin",
      "Helicopter Shot|Finish",
      "Super Over|Tie",
      "Free Hit|Bonus",
      "LBW|Pad",
      "Duck|Zero",
      "Hat-trick|Three",
      "Third Umpire|Replay",
      "Gully Cricket|Street",
      "Tennis Ball|Rubber",
      "Eden Gardens|Kolkata",
      "Wankhede|Mumbai",
      "India vs Pakistan|Rivalry",
      "Commentary|Voice",
      "Cheerleaders|Dance",
      "Strategic Timeout|Break",
      "Run Out|Throw",
      "Stumps|Wood",
      "Powerplay|Fielding",
      "Orange Cap|Runs",
      "Test Match|Five",
      "Sledging|Words",
      "Dressing Room|Balcony",
      "One Tip One Hand|Rule",
      "Pehli Ball Trial|Rule",
      "Chhat Pe Gayi Toh Out|Rule",
      "Jo Maarega Wohi Laayega|Ball",
      "Last Man Batting|Alone",
    ],
  },
  {
    id: "festivals",
    label: "Tyohaar",
    emoji: "🪔",
    tone: "yellow",
    desi: true,
    words: [
      "Diwali Ki Safai|Dusting",
      "Patakhe|Noise",
      "Rangoli|Floor",
      "Diya|Oil",
      "Laxmi Puja|Wealth",
      "Diwali Wali Teen Patti|Cards",
      "Soan Papdi|Regift",
      "Gujiya|Holi",
      "Pichkari|Water",
      "Gulaal|Colour",
      "Bhang|Thandai",
      "Karva Chauth|Moon",
      "Chalni|Sieve",
      "Rakhi|Thread",
      "Raksha Bandhan Ka Gift|Sister",
      "Garba|Circle",
      "Dandiya|Sticks",
      "Falguni Pathak|Navratri",
      "Pandal Hopping|Kolkata",
      "Ganpati Visarjan|Sea",
      "Modak|Sweet",
      "Sewaiyan|Eid",
      "Eidi|Money",
      "Lohri Ka Bonfire|Fire",
      "Rewri|Winter",
      "Patang|Kite",
      "Manjha|Cut",
      "Dahi Handi|Pyramid",
      "Ravan Dahan|Effigy",
      "Ramleela|Stage",
      "Thekua|Chhath",
      "Onam Sadya|Banana leaf",
      "Pongal|Pot",
      "Christmas Plum Cake|Bakery",
      "Bhai Dooj|Tilak",
      "Dhanteras|Shopping",
    ],
  },
  {
    id: "wedding",
    label: "Shaadi season",
    emoji: "💍",
    tone: "pink",
    desi: true,
    words: [
      "Mehendi|Hands",
      "Haldi|Yellow",
      "Sangeet|Dance",
      "Baraat|Road",
      "Ghodi|Groom",
      "Joota Chupai|Shoes",
      "Pheras|Seven",
      "Vidaai|Tears",
      "Varmala|Lift",
      "Sehra|Face",
      "Shagun Ka Lifafa|101",
      "Buffet Ki Line|Plates",
      "Paneer Ka Counter|Food",
      "Kulfi Counter|Dessert",
      "DJ Wale Babu|Music",
      "Nagin Dance|Floor",
      "Fufaji Naraz Hain|Sulking",
      "Kundli Milan|Stars",
      "Saali|Jija",
      "Lehenga|Heavy",
      "Sherwani|Groom",
      "Photographer Bhaiya|Pose",
      "Drone Camera|Sky",
      "Pre-Wedding Shoot|Couple",
      "Shaadi Ka Card|Invite",
      "Stage Pe Photo|Queue",
      "Band Baaja|Brass",
      "Light Wale Uncle|Head",
      "Mandap|Fire",
      "Pandit Ji|Mantras",
      "Kaleere|Bride",
      "Sindoor|Red",
      "Mangalsutra|Necklace",
      "Honeymoon|Trip",
      "Shaadi.com|Profile",
    ],
  },
  {
    id: "desi-ghar",
    label: "Desi ghar",
    emoji: "🏠",
    tone: "blue",
    desi: true,
    words: [
      "Pressure Cooker|Whistle",
      "Steel Almirah|Locker",
      "Chappal|Mummy",
      "Tiffin|Office",
      "Ice Cream Tub|Lies",
      "Plastic Bag Stash|Kitchen",
      "TV Remote|Plastic",
      "Diwan|Storage",
      "Mosquito Racket|Zap",
      "Good Knight|Plug",
      "Geyser|Winter",
      "Water Tank|Roof",
      "Pooja Thali|Bell",
      "Tulsi Plant|Courtyard",
      "Bucket & Mug|Bath",
      "Rajai|Winter",
      "Charpai|Rope",
      "Desert Cooler|Summer",
      "Inverter|Power",
      "Mixer Grinder|Noise",
      "Tawa|Iron",
      "Belan|Weapon",
      "Masala Dabba|Spices",
      "Steel Glass|Tumbler",
      "Calendar|Wall",
      "Doormat|Entrance",
      "Old Newspapers|Raddi",
      "Biscuit Tin|Sewing",
      "Shoe Rack|Door",
      "Balcony|Clothes",
      "Doodhwala|Morning",
      "Kaamwali Bai|Leave",
      "Sofa Cover|Plastic",
      "Landline|Wire",
      "Hing|Smell",
    ],
  },
  {
    id: "desi-life",
    label: "Desi life",
    emoji: "🫖",
    tone: "purple",
    desi: true,
    words: [
      "Sharma Ji Ka Beta|Topper",
      "Log Kya Kahenge|Society",
      "Board Exams|Pressure",
      "IIT-JEE|Coaching",
      "Kota|Students",
      "Engineer|Default",
      "Arranged Marriage|Parents",
      "Joint Family|Crowd",
      "Relatives' Questions|Marks",
      "Tuition|Evening",
      "Report Card|Signature",
      "Summer Vacation|Nani",
      "Nani Ka Ghar|Mangoes",
      "Train Journey|Berth",
      "Tatkal Booking|Rush",
      "Jugaad|Fix",
      "Bargaining|Price",
      "Indian Standard Time|Late",
      "WhatsApp Uncle|Forward",
      "Good Morning Message|Flowers",
      "Family Group|Chat",
      "Nazar|Lemon",
      "Kitty Party|Ladies",
      "Gossip Aunty|Balcony",
      "Free Advice|Everyone",
      "Chai Break|Office",
      "Middle-class Dad|Lights",
      "Guest Arrival|Cleaning",
      "Doctor or Engineer|Career",
      "Green Card|Abroad",
      "NRI|Visit",
      "Sunday Cleaning|Fans",
      "Load Shedding|Candle",
      "Ghar Ka Khana|Mom",
      "Pocket Money|Weekly",
    ],
  },
  {
    id: "desi-tv",
    label: "TV & OTT",
    emoji: "📺",
    tone: "orange",
    desi: true,
    words: [
      "Jethalal|Gada",
      "Daya Ben|Garba",
      "Babita Ji|Neighbour",
      "Tapu Sena|Kids",
      "Gokuldham Society|Mumbai",
      "Gopi Bahu|Laptop",
      "Kokila Ben|Rasoda",
      "Tulsi Virani|Saas",
      "Anupamaa|Serial",
      "Naagin|Snake",
      "ACP Pradyuman|Gadbad",
      "Daya Darwaza Tod|Kick",
      "Shaktimaan|Sorry",
      "Kaun Banega Crorepati|Lifeline",
      "Bigg Boss|House",
      "Roadies|Gang leader",
      "Splitsvilla|Villa",
      "Shark Tank India|Pitch",
      "Indian Idol|Sad story",
      "Kapil Sharma Show|Comedy",
      "Sarabhai vs Sarabhai|Middle class",
      "Khichdi (TV)|Hansa",
      "Panchayat|Phulera",
      "Sachiv Ji|Village",
      "Kaleen Bhaiya|Carpet",
      "Guddu Bhaiya|Gym",
      "Munna Tripathi|Mirzapur",
      "Ganesh Gaitonde|Sacred",
      "Harshad Mehta|Market",
      "Srikant Tiwari|Spy",
      "Jeetu Bhaiya|Kota",
      "Gullak|Family",
      "Aashram|Baba",
      "Kota Factory|Coaching",
      "Pitchers|Startup",
      "Rasode Mein Kaun Tha|Kitchen",
    ],
  },
  {
    id: "india-places",
    label: "Places in India",
    emoji: "🗺️",
    tone: "green",
    desi: true,
    words: [
      "Goa|Beach",
      "Taj Mahal|Marble",
      "Ladakh|Bikes",
      "Kerala|Backwaters",
      "Jaipur|Pink",
      "Varanasi|Ghats",
      "Manali|Snow",
      "Rishikesh|Rafting",
      "Mumbai|Local",
      "Delhi|Traffic",
      "Bangalore|Tech",
      "Kolkata|Tram",
      "Hyderabad|Pearls",
      "Chennai|Marina",
      "Shimla|Mall Road",
      "Darjeeling|Tea",
      "Andaman|Islands",
      "Kashmir|Shikara",
      "Amritsar|Gold",
      "Udaipur|Lakes",
      "Mysore|Palace",
      "Ooty|Toy Train",
      "Gateway of India|Pigeons",
      "Marine Drive|Necklace",
      "India Gate|Memorial",
      "Qutub Minar|Tower",
      "Red Fort|Flag",
      "Chandni Chowk|Paranthe",
      "Connaught Place|Circles",
      "Hampi|Ruins",
      "Rann of Kutch|White",
      "Statue of Unity|Tall",
      "Kedarnath|Trek",
      "Golden Temple|Langar",
      "Juhu Beach|Snacks",
      "Lonavala|Chikki",
    ],
  },
  {
    id: "street",
    label: "Gali & bazaar",
    emoji: "🛺",
    tone: "yellow",
    desi: true,
    words: [
      "Auto Rickshaw|Meter",
      "Chaiwala|Kettle",
      "Paan Shop|Red",
      "Mumbai Local|Crowd",
      "Metro|Card",
      "Kirana Store|Credit",
      "Sabziwala|Cart",
      "Traffic Jam|Honk",
      "Cow on Road|Holy",
      "Speed Breaker|Bump",
      "Pothole|Rain",
      "Toll Plaza|Queue",
      "Dhaba|Highway",
      "Sarojini Nagar|Bargain",
      "Juice Centre|Fresh",
      "Ganna Juice|Machine",
      "Kulfi Wala|Bell",
      "Mochi|Repair",
      "Dhobi|Iron",
      "Recharge Shop|Mobile",
      "Xerox Shop|Copies",
      "Cycle Rickshaw|Pedal",
      "Tempo|Loud",
      "Ola Uber|App",
      "Swiggy Delivery|Bag",
      "Barber Shop|Chair",
      "Mandir Bell|Morning",
      "Street Dog|Loyal",
      "Truck Art|Horn OK",
      "Rangoli Seller|Powder",
      "Halwai|Sweets",
    ],
  },
  {
    id: "desi-brands",
    label: "Snacks & brands",
    emoji: "🛍️",
    tone: "red",
    desi: true,
    words: [
      "Parle-G|Biscuit",
      "Good Day|Cashew",
      "Marie Gold|Chai",
      "Monaco|Salty",
      "Krackjack|Sweet-salty",
      "Hide & Seek Biscuit|Chocolate chip",
      "Bourbon|Cream",
      "Haldiram's Bhujia|Namkeen",
      "Kurkure|Crunch",
      "Lays Magic Masala|Blue",
      "Bingo Mad Angles|Triangle",
      "Act II Popcorn|Microwave",
      "Dairy Milk|Purple",
      "5 Star|Caramel",
      "Perk|Light",
      "Munch|Crunch",
      "Pulse Candy|Kachcha aam",
      "Alpenliebe|Toffee",
      "Center Fresh|Gum",
      "Thums Up|Toofani",
      "Limca|Lemon",
      "Maaza|Mango",
      "Frooti|Mango",
      "Rooh Afza|Summer",
      "Amul Butter|Utterly",
      "Mother Dairy|Booth",
      "Kwality Walls|Ice cream",
      "Cornetto|Cone",
      "Amul Kool|Milk",
      "Bikaji|Namkeen",
      "Tang|Orange",
      "Nutella|Spread",
      "Paper Boat|Aamras",
      "Real Juice|Tetrapack",
      "Daag Achhe Hain|Kids",
    ],
  },
  {
    id: "mythology",
    label: "Mythology & epics",
    emoji: "🪷",
    tone: "purple",
    desi: true,
    words: [
      "Hanuman|Strength",
      "Ravan|Ten",
      "Ram|Bow",
      "Sita|Exile",
      "Lakshman|Line",
      "Krishna|Flute",
      "Arjun|Archer",
      "Draupadi|Five",
      "Bhishma|Oath",
      "Karna|Generous",
      "Duryodhan|Pride",
      "Shakuni|Dice",
      "Ganesh|Elephant",
      "Shiva|Snake",
      "Durga|Tiger",
      "Kali|Tongue",
      "Lakshmi|Wealth",
      "Saraswati|Veena",
      "Brahma|Creator",
      "Vishnu|Conch",
      "Kumbhkaran|Sleep",
      "Ekalavya|Thumb",
      "Abhimanyu|Trap",
      "Pandavas|Brothers",
      "Kauravas|Hundred",
      "Pushpak Vimaan|Flying",
      "Sudarshan Chakra|Spinning",
      "Kurukshetra|Battle",
      "Ram Setu|Bridge",
      "Sanjeevani|Mountain",
      "Narad Muni|Gossip",
      "Kamdhenu|Cow",
      "Amrit|Immortal",
      "Indra|Rain",
    ],
  },
  {
    id: "food",
    label: "Food",
    emoji: "🍕",
    tone: "orange",
    desi: false,
    words: [
      "Pizza|Slice",
      "Burger|Bun",
      "Sushi|Raw",
      "Pasta|Italian",
      "Tacos|Mexico",
      "Ice Cream|Cone",
      "Chocolate|Melt",
      "Popcorn|Movie",
      "French Fries|Salty",
      "Pancakes|Stack",
      "Doughnut|Hole",
      "Hot Dog|Sausage",
      "Sandwich|Layers",
      "Salad|Bowl",
      "Steak|Grill",
      "Omelette|Pan",
      "Croissant|Flaky",
      "Cheesecake|Slice",
      "Noodles|Slurp",
      "Waffles|Grid",
      "Nachos|Cheese",
      "Brownie|Square",
      "Popsicle|Stick",
      "Cupcake|Frosting",
      "Fried Chicken|Bucket",
      "Watermelon|Seeds",
      "Coconut|Hard",
      "Mango|King",
      "Coffee|Morning",
      "Cotton Candy|Fair",
    ],
  },
  {
    id: "animals",
    label: "Animals",
    emoji: "🐘",
    tone: "green",
    desi: false,
    words: [
      "Elephant|Trunk",
      "Tiger|Stripes",
      "Peacock|Feathers",
      "Monkey|Banana",
      "Cobra|Hood",
      "Camel|Desert",
      "Penguin|Ice",
      "Giraffe|Tall",
      "Kangaroo|Pouch",
      "Dolphin|Smart",
      "Shark|Fin",
      "Owl|Night",
      "Parrot|Talk",
      "Crocodile|Teeth",
      "Panda|Bamboo",
      "Lion|King",
      "Cow|Milk",
      "Buffalo|Slow",
      "Donkey|Load",
      "Pigeon|City",
      "Crow|Black",
      "Lizard|Wall",
      "Cockroach|Survive",
      "Mosquito|Bite",
      "Butterfly|Colours",
      "Spider|Web",
      "Octopus|Arms",
      "Zebra|Pattern",
      "Bat|Upside",
      "Snail|Slow",
    ],
  },
  {
    id: "jobs",
    label: "Jobs",
    emoji: "🧑‍⚕️",
    tone: "blue",
    desi: false,
    words: [
      "Doctor|Hospital",
      "Teacher|Class",
      "Pilot|Sky",
      "Chef|Kitchen",
      "Police Officer|Uniform",
      "Firefighter|Hose",
      "Software Engineer|Laptop",
      "CA|Taxes",
      "Lawyer|Court",
      "Dentist|Teeth",
      "Barber|Scissors",
      "Tailor|Measure",
      "Farmer|Fields",
      "Astronaut|Space",
      "Photographer|Lens",
      "YouTuber|Subscribe",
      "Delivery Boy|Bike",
      "Security Guard|Gate",
      "Plumber|Pipes",
      "Electrician|Wires",
      "Postman|Letters",
      "Pandit|Rituals",
      "Wedding Planner|Event",
      "Cricketer|Bat",
      "Magician|Trick",
      "Air Hostess|Flight",
      "Judge|Hammer",
      "Bus Conductor|Tickets",
      "Journalist|News",
      "Influencer|Reels",
    ],
  },
  {
    id: "places",
    label: "Places",
    emoji: "📍",
    tone: "yellow",
    desi: false,
    words: [
      "Airport|Gate",
      "Hospital|Beds",
      "School|Bell",
      "Cinema|Screen",
      "Gym|Sweat",
      "Library|Quiet",
      "Beach|Sand",
      "Mall|Escalator",
      "Temple|Shoes",
      "Railway Station|Platform",
      "Zoo|Cages",
      "Museum|History",
      "Hotel|Room",
      "Restaurant|Menu",
      "Bank|Queue",
      "Park|Bench",
      "Office|Desk",
      "Hostel|Roommates",
      "Prison|Bars",
      "Swimming Pool|Chlorine",
      "Circus|Tent",
      "Space Station|Orbit",
      "Water Park|Slides",
      "Supermarket|Trolley",
      "Wedding Hall|Stage",
      "Stadium|Crowd",
      "Petrol Pump|Fuel",
      "Salon|Mirror",
      "Bakery|Oven",
      "Haunted House|Scary",
    ],
  },
  {
    id: "things",
    label: "Everyday things",
    emoji: "📱",
    tone: "white",
    desi: false,
    words: [
      "Phone|Screen",
      "Umbrella|Rain",
      "Toothbrush|Morning",
      "Mirror|Reflection",
      "Pillow|Soft",
      "Headphones|Music",
      "Charger|Battery",
      "Wallet|Cards",
      "Sunglasses|Sun",
      "Backpack|Straps",
      "Keys|Lock",
      "Watch|Wrist",
      "Candle|Wax",
      "Scissors|Cut",
      "Ceiling Fan|Spin",
      "Fridge|Cold",
      "Laptop|Work",
      "Toilet Paper|Roll",
      "Comb|Hair",
      "Helmet|Head",
      "Bicycle|Pedal",
      "Torch|Light",
      "Camera|Click",
      "Remote|Buttons",
      "Socks|Pair",
      "Lipstick|Red",
      "Perfume|Smell",
      "Water Bottle|Sip",
      "Alarm Clock|Snooze",
      "Selfie Stick|Reach",
    ],
  },
  {
    id: "movies",
    label: "Hollywood & shows",
    emoji: "🍿",
    tone: "purple",
    desi: false,
    words: [
      "Titanic|Ship",
      "Harry Potter|Wand",
      "Avengers|Team",
      "Spider-Man|Web",
      "Batman|Night",
      "Frozen|Ice",
      "The Lion King|Pride",
      "Jurassic Park|Dinosaurs",
      "Star Wars|Galaxy",
      "Friends|Coffee",
      "Game of Thrones|Throne",
      "Stranger Things|Upside",
      "Money Heist|Masks",
      "Squid Game|Games",
      "Breaking Bad|Chemistry",
      "Shrek|Swamp",
      "Toy Story|Toys",
      "Finding Nemo|Fish",
      "Barbie|Pink",
      "Oppenheimer|Bomb",
      "Avatar|Blue",
      "Fast & Furious|Cars",
      "Mr. Bean|Teddy",
      "Tom and Jerry|Chase",
      "The Office|Paper",
      "Interstellar|Space",
      "Home Alone|Christmas",
      "Pirates of the Caribbean|Ship",
      "Joker|Smile",
      "Wednesday|Dance",
    ],
  },
  {
    id: "sports",
    label: "Sports & games",
    emoji: "⚽",
    tone: "blue",
    desi: false,
    words: [
      "Football|Goal",
      "Kabaddi|Breath",
      "Kho-Kho|Chase",
      "Badminton|Shuttle",
      "Chess|King",
      "Carrom|Striker",
      "Ludo|Dice",
      "Snakes & Ladders|Board",
      "Hockey|Stick",
      "Tennis|Racket",
      "Boxing|Gloves",
      "Wrestling|Mat",
      "Swimming|Water",
      "Marathon|Long",
      "Gilli Danda|Stick",
      "Pithoo|Stones",
      "Hide & Seek|Count",
      "Antakshari|Songs",
      "Kite Flying|Manjha",
      "PUBG|Chicken",
      "Volleyball|Net",
      "Basketball|Hoop",
      "Table Tennis|Paddle",
      "Formula 1|Speed",
      "Golf|Hole",
      "Yoga|Mat",
      "Musical Chairs|Music",
      "Uno|Cards",
      "Teen Patti|Cards",
      "Bowling|Pins",
    ],
  },
];

export const DEFAULT_CATEGORY_IDS = imposterCategories
  .filter((c) => c.desi)
  .map((c) => c.id);

const byId = new Map(imposterCategories.map((c) => [c.id, c]));

export function imposterCategory(id: string) {
  return byId.get(id);
}

export function parseEntry(entry: string, categoryId: string): ImposterWord {
  const [word, hint = ""] = entry.split("|");
  return { word: word.trim(), hint: hint.trim(), categoryId };
}

/** Every word in the chosen categories. */
export function imposterPool(categoryIds: string[]): ImposterWord[] {
  return categoryIds.flatMap((id) => {
    const category = byId.get(id);
    return category ? category.words.map((w) => parseEntry(w, id)) : [];
  });
}
